### ISSUE TITLE
Persistence for LogisticRegressor

### ISSUE THREAD

**Issue by jurrdb** [gyrdym/ml_algo#125]
Hello,
At the moment I have to retrain the model each time I use it. Fortunately, this does not take a lot of time, but because of that all sample data has to be present anywhere the model is used. One workaround that I found is to manually initialize a LinearRegressorImpl object with coefficients obtained from a trained LogisticRegressor model. However, this requires importing package private files which is not ideal. Adding a way to persist regressor models would be a great improvement!

Best regards.

**Comment by gyrdym** [comment]
@jurrdb Hello,

Thank you for creating the issue.

Please, check out the desired [functionality](https://pub.dev/documentation/ml_algo/latest/ml_algo/LogisticRegressor/LogisticRegressor.fromJson.html) - I've added `LogisticRegressor.saveAsJson(...)` method in order to store the fitted model as json, and in order to restore the model you may use `LogisticRegressor.fromJson(...)` constructor. You can find more details in the link above.

**Comment by jurrdb** [comment]
@gyrdym Thanks a lot for adding that functionality! I tested it in my project and it works like a charm.
